use_frameworks!

target 'HLQRCodeScanner_Example' do
  pod 'HLQRCodeScanner', :path => '../'

  target 'HLQRCodeScanner_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
